### PR TITLE
Review Output & Resources section - fix some typos, suggest amends

### PR DESCRIPTION
**Pull request by Phippsy**
Hope this is useful - note that I added a <div> tag to rmarkdown-shiny.Rmd which might be a step too far.

### CODE REVIEW

**Comment by gilliganondata** [comment]
Outstanding! Thanks! I'll leave it to Mark to merge, as I'm liable to bork things in the process. :-)

**Comment by Phippsy** [comment]
My pleasure, long overdue. Will try to work through some more & add if I see anything useful. a `<div>` tag is I added to rmarkdown-shiny.Rmd, to try to distinguish the boilerplate.

**Comment by MarkEdmondson1234** [comment]
TY 👍 :)

**Comment by Phippsy** [comment]
Great - thanks, gents - delighted to make a contribution. Have a good one.

**Pull request merged**
